### ISSUE TITLE
ByJG\ApiTools\Exception\GenericSwaggerException: Not all cases are defined.

### ISSUE THREAD

**Issue by karlos1338** [byjg/php-swagger-test#34]
Hi,

first: thanks for this great lib!

**I get the following error message**
`ByJG\ApiTools\Exception\GenericSwaggerException: Not all cases are defined. Please open an issue about this. Schema: devices`

**Test**
```
$request = new ApiRequester();
        $request
            ->withMethod("PUT")
            ->withPath("/api/devices")
            ->withRequestBody(array("devices" => array("action" => "switch", "global_id"=> "DreamboxWohnzimmer", "state"=> "on")));

        $this->assertRequest($request);
```

**Controller**

```
/**
     * Change state(s) of specified devices or notify websocket for changes of specified devices
     * @Rest\Route("/api/devices", methods={"PUT"}, name="api_electricity_device_action"),
     *
     * @SWG\Tag(name="Devices"),
     *
     * @SWG\Parameter(name="body", in="body", description="JSON payload", required=true,
     *     @SWG\Schema(type="object",
     *          @SWG\Property(property="devices", type="array",
     *              @SWG\Items(type="object",
     *                  @SWG\Property(property="action", type="string", enum={"switch", "notify"}, example="switch"),
     *                  @SWG\Property(property="global_id", description="global_id of affected device", type="string",),
     *                  @SWG\Property(property="state", description="new state", type="string"),
     *                  @SWG\Property(property="parameter", description="used for further information (sonos group, yamaha specific input, hue brightness)", type="string", example="brightness"),
     *              )
     *          )
     *      )
     * ),
     * @SWG\Response(response="200", description="Returned when changing states was successful",
     *     @SWG\Schema(type="object",
     *         @SWG\Property(property="global_id", ref=@Model(type=Device::class))
     *     )
     * ),
     *
     * @SWG\Response(response="400", description="Returned when error occured (e.g. parameter missing)",
     *     @SWG\Schema(ref="#/definitions/Error")
     * ),
     *
     * @SWG\Response(response="404", description="Returned when device not found",
     *     @SWG\Schema(ref="#/definitions/Error")
     * )
     */
```

Did I do something wrong?

**Comment by byjg** [comment]
I believe the definition is wrong. Unfortunately the Swagger project is not clear on that. I prefer in that case instead of define all properties, create a definition of `device` and use as the following:

```
     * @SWG\Parameter(name="body", in="body", description="JSON payload", required=true,
     *     @SWG\Schema(
     *          @SWG\Property(property="devices", type="array",
     *              @SWG\Items(ref="#/definitions/device")
     *      )
     * ),
```

**Comment by karlos1338** [comment]
Thanks for the idea.

I tried it - but I cant get it to work. I seem to be blind.

**Definition**
```
Devices:
                description: "devices"
                type: object
                properties:
                    action:
                        type: string
                        example: switch
                    global_id:
                        type: string
                        example: DreamboxWohnzimmer
                    state:
                        type: string
                        example: on
                    parameter:
                        type: string
                        example: brightness
```

**Controller**
```
* @SWG\Parameter(name="body", in="body", description="JSON payload", required=true,
     *     @SWG\Schema(type="object",
     *         @SWG\Property(property="devices", ref="#/definitions/Devices")
     *     )
     * ),
```

**Test**
```
$request = new SwaggerRequester();
        $request
            ->withMethod("PUT")

            ->withPath("/api/devices")
            ->withRequestBody(array("devices" => [array("action" => "switch", "global_id" => "DreamboxWohnzimmer", "state" => "on")]));
         //   ->withRequestBody($hi);

        $this->assertRequest($request);
```

**Result**

```
1) App\Tests\Controller\DeviceGroupsControllerTest::testCreateDeviceGroup
ByJG\Swagger\Exception\NotMatchedException: The property(ies) '0' has not defined in '#/definitions/Devices' ->
[
    {
        "action": "switch",
        "global_id": "DreamboxWohnzimmer",
        "state": "on"
    }
]
```

I need devices to be an array, because it could be multiple to set.. Correct would be..

```
{
  "devices": [{
    "action": "switch",
    "global_id": "DreamboxWohnzimmer",
    "state": "on",
    "parameter": "brightness"
  }]
}
```
